#!/bin/bash
# ARACNe-AP network inference — LumA, LumB, Her2 (TCGA + METABRIC)
# Same parameters as run_aracne_ap.sh (see Kbhb/run_aracne_ap.sh and the
# parameter documentation in the results notes): --pvalue 1E-8, 100
# bootstraps, seed 1.
#
# Inputs  (generated by luminal_her2_pre_networks.R):
#   data/tcga_{subtype}_matrix.txt   data/mtbrc_{subtype}_matrix.txt
#   data/TFs_Lambert2018.txt
#
# Outputs:
#   data/tcga_{subtype}_network.txt   data/mtbrc_{subtype}_network.txt
#
# Runs the 6 networks SEQUENTIALLY (one at a time), each one using up to
# N_CORES for the bootstraps, respecting the session core limit.

set -euo pipefail

ARACNE=/STORAGE/genut/software/ARACNe-AP/dist/aracne.jar
TFFILE=data/TFs_Lambert2018.txt
N_BOOTSTRAPS=100
N_CORES=70
MEM_BOOT=4G
MEM_FULL=32G

JVM_SINGLE="-XX:+UseSerialGC -XX:ActiveProcessorCount=1 -Djava.util.concurrent.ForkJoinPool.common.parallelism=1"

run_one() {
  local EXPFILE=$1
  local OUTDIR=$2
  local FINALNET=$3
  local LABEL=$4

  mkdir -p "$OUTDIR"

  echo "[$(date)] ${LABEL} — computing MI threshold..."
  java -Xmx${MEM_FULL} -jar "$ARACNE" \
      -e "$EXPFILE" -o "$OUTDIR" --tfs "$TFFILE" \
      --pvalue 1E-8 --seed 1 --calculateThreshold

  echo "[$(date)] ${LABEL} — ${N_BOOTSTRAPS} bootstraps with ${N_CORES} cores..."
  seq 1 "$N_BOOTSTRAPS" | xargs -P "$N_CORES" -I{} \
      java -Xmx${MEM_BOOT} ${JVM_SINGLE} -jar "$ARACNE" \
          -e "$EXPFILE" -o "$OUTDIR" --tfs "$TFFILE" \
          --pvalue 1E-8 --seed {}

  echo "[$(date)] ${LABEL} — consolidating..."
  java -Xmx${MEM_FULL} -jar "$ARACNE" \
      -e "$EXPFILE" -o "$OUTDIR" --consolidate

  cp "$OUTDIR/network.txt" "$FINALNET"
  echo "[$(date)] ${LABEL} — network saved to ${FINALNET}"
}

for SUB in LumA LumB Her2; do
  run_one "data/tcga_${SUB}_matrix.txt"  "data/tcga_${SUB}_aracne_ap_output"  "data/tcga_${SUB}_network.txt"  "TCGA ${SUB}"
  run_one "data/mtbrc_${SUB}_matrix.txt" "data/mtbrc_${SUB}_aracne_ap_output" "data/mtbrc_${SUB}_network.txt" "METABRIC ${SUB}"
done

echo "[$(date)] === ARACNE-AP COMPLETE (6 networks: LumA/LumB/Her2 x TCGA/METABRIC) ==="
